name: CIRELEASE

on:
  push:
    branches:
      - main

jobs:
  pre-release:
    name: Pre-Release
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d_%s')"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm ci

      - name: Build App
        run: npm run alpdeskfee

      - run: mkdir -p artifact

      - name: Zip
        if: success()
        uses: montudor/action-zip@v1
        with:
          args: zip -qq -r artifact/release_alpdeskfee-client_${{ steps.date.outputs.date }}.zip dist/elements

      - name: Upload
        if: success()
        uses: actions/upload-artifact@v2
        with:
          name: release_alpdeskfee-client_${{ steps.date.outputs.date }}.zip
          path: artifact/release_alpdeskfee-client_${{ steps.date.outputs.date }}.zip

      - name: Release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ steps.date.outputs.date }}
          prerelease: true
          title: Master-${{ steps.date.outputs.date }}
          files: |
            artifact/release_alpdeskfee-client_${{ steps.date.outputs.date }}.zip
